import test from 'node:test';import assert from 'node:assert/strict';import{mkdtemp,mkdir}from'node:fs/promises';import{tmpdir}from'node:os';import{join}from'node:path';import{Vault,SearchIndex}from'@bastra-recall/core';import{captureDraft,draftId,draftFingerprint,listDrafts}from'../src/draft-store.js';import{recordDraftHints,recordDraftUse}from'../src/draft-use.js';import{Telemetry}from'../src/telemetry.js';import{startHttpServer}from'../src/http.js';
test('HTTP cannot manufacture a draft display for an unissued session',async()=>{
 const dir=await mkdtemp(join(tmpdir(),'review-hinted-')),root=join(dir,'vault');await mkdir(root);const previous=process.env.BASTRA_DRAFTS_PATH;process.env.BASTRA_DRAFTS_PATH=join(dir,'drafts.json');const v=new Vault(root);await v.init();const search=new SearchIndex(v);search.start();const telemetry=new Telemetry();const now=Date.now(),quote='Our invented spectrometer calibration requires packet7.conf and tungsten reference lamps.',fp=draftFingerprint(quote),id=draftId('origin',0,fp);
 await captureDraft({id,fp,quote,kind:'typed',situation:{before:[],after:['cat packet7.conf'],reads:[],lits:[]},evidence:[{session_id:'origin',turn:0,ts:now}],created:now,last_touched:now,surfaced:[],state:'open'});
 const server=await startHttpServer({port:0,vault:v,search,telemetry,version:'fixture',toolDeps:{vault:v,search,telemetry,vaultPath:root},documentWriteEnabled:false,embedding:{on:false,providerId:null,source:'none'}});
 try{const r=await fetch(`http://127.0.0.1:${server.port}/hook/hinted`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({session_id:'forged',ids:[],draft_ids:[id],draft_input:'calibration'})});assert.equal((await r.json() as any).drafts_counted,undefined);assert.equal((await listDrafts())[0].surfaced.length,0);}finally{await server.close();search.stop();await v.stop();if(previous===undefined)delete process.env.BASTRA_DRAFTS_PATH;else process.env.BASTRA_DRAFTS_PATH=previous;}
});
test('draft metadata fields cannot introduce control characters',async()=>{
 const dir=await mkdtemp(join(tmpdir(),'review-fields-'));const previous=process.env.BASTRA_DRAFTS_PATH;process.env.BASTRA_DRAFTS_PATH=join(dir,'drafts.json');const now=Date.now(),quote='Our invented spectrometer calibration requires packet7.conf and tungsten reference lamps.',fp=draftFingerprint(quote),id=draftId('origin',0,fp);
 try{await captureDraft({id,fp,quote,kind:'typed',situation:{before:[],after:['cat packet7.conf'],reads:[],lits:[],project:'fixture\nspoof'},evidence:[{session_id:'origin\nspoof',turn:0,ts:now,client:'codex\rspoof'}],created:now,last_touched:now,surfaced:[],state:'open'});await recordDraftHints([id],'reader\nspoof','calibration',now+10);await recordDraftUse({sessionId:'reader\nspoof',toolName:'Bash\nspoof',excerpt:'cat packet7.conf',exitCode:0,now:now+20});const row=(await listDrafts(now+20))[0];assert.ok(!/[\r\n]/.test(row.evidence[0].session_id));assert.ok(!/[\r\n]/.test(row.evidence[0].client!));assert.ok(!/[\r\n]/.test(row.surfaced[0].used!.tool));assert.ok(!/[\r\n]/.test(row.situation.project!));}finally{if(previous===undefined)delete process.env.BASTRA_DRAFTS_PATH;else process.env.BASTRA_DRAFTS_PATH=previous;}
});
