import test from "node:test";
import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { mkdir, mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";

test("temporary library vaults leave the default root history untouched; explicit markers persist them", async (t) => {
  const base = await mkdtemp(join(tmpdir(), "bastra-temp-history-"));
  t.after(() => rm(base, { recursive: true, force: true }));
  const home = join(base, "home");
  const temp = join(base, "tmp");
  await mkdir(home);
  await mkdir(temp);
  const env: NodeJS.ProcessEnv = { ...process.env, HOME: home, USERPROFILE: home, TMPDIR: temp, TEMP: temp, TMP: temp };
  delete env.NODE_TEST_CONTEXT;
  delete env.BASTRA_VAULT_ROOTS_PATH;
  const guard = new URL("../src/vault-root-guard.ts", import.meta.url).href;
  const vault = new URL("../src/vault.ts", import.meta.url).href;
  const output = execFileSync(process.execPath, ["--import", "tsx", "--input-type=module", "-e", `
    import assert from 'node:assert/strict';
    import { existsSync } from 'node:fs';
    import { mkdir, readFile, rm, symlink, writeFile } from 'node:fs/promises';
    import { homedir, tmpdir } from 'node:os';
    import { join, parse } from 'node:path';
    const { Vault } = await import(${JSON.stringify(vault)});
    const { ensureVaultDir, noteVaultRootPresent } = await import(${JSON.stringify(guard)});
    const state = join(homedir(), '.bastra');
    const marker = join(state, 'vault-roots.json');
    const fixture = join(tmpdir(), 'reader');
    await mkdir(fixture);
    await new Vault(fixture).init();
    assert.equal(existsSync(state), false, 'a read-only temp vault creates no state in HOME');
    await mkdir(state);
    const sentinel = JSON.stringify({ '/known-vault': { first_seen: '2026-10-04' } });
    await writeFile(marker, sentinel);
    await ensureVaultDir(fixture, join(fixture, 'memories'));
    assert.equal(await readFile(marker, 'utf8'), sentinel, 'a temp writer preserves real-root history');
    await rm(fixture, { recursive: true });
    await assert.rejects(ensureVaultDir(fixture, fixture, { createRoot: true }), { code: 'VAULT_MISSING' });
    const persistentAlias = join(tmpdir(), 'persistent-alias');
    await symlink(parse(process.cwd()).root, persistentAlias, 'junction');
    noteVaultRootPresent(persistentAlias);
    assert.ok(JSON.parse(await readFile(marker, 'utf8'))[persistentAlias], 'a temp symlink onto a persistent directory still records it');
    await mkdir(fixture);
    process.env.BASTRA_VAULT_ROOTS_PATH = join(tmpdir(), 'explicit-marker.json');
    noteVaultRootPresent(fixture);
    assert.ok(JSON.parse(await readFile(process.env.BASTRA_VAULT_ROOTS_PATH, 'utf8'))[fixture]);
    console.log('ok');
  `], { env, encoding: "utf8" });
  assert.equal(output.trim(), "ok");
});
